"use client";

import { useState } from "react";
import { Building2, KeyRound, Pencil, UserRound } from "lucide-react";
import { ChangePasswordForm } from "@/components/settings/change-password-form";
import { EditProfileForm } from "@/components/settings/edit-profile-form";
import { signOut } from "@/lib/auth-client";

type Store = { id: string; name: string; address: string | null; createdAt: Date };
export function EmployeeProfile({ user, stores }: { user: { name: string; email: string; role: string }; stores: Store[] }) {
  const [tab, setTab] = useState<"profile" | "stores">("profile"); const [edit, setEdit] = useState(false); const [password, setPassword] = useState(false);
  return <div className="min-h-screen bg-[#f5f6f7] text-[#253049]"><header className="flex h-16 items-center border-b bg-white px-6"><img src="/korgen-kassa-mark.png" alt="Korgen Kassa" className="h-8 w-8 rounded-lg object-contain" /><span className="ml-2 text-sm font-bold text-[#15503A]">Korgen Kassa</span><button onClick={() => signOut().then(() => { window.location.href = "/login"; })} className="ml-auto text-sm text-slate-500 hover:text-slate-900">Выйти</button></header><div className="border-b bg-white px-6"><div className="flex gap-1"><Tab active={tab === "profile"} onClick={() => setTab("profile")}>Профиль</Tab><Tab active={tab === "stores"} onClick={() => setTab("stores")}>Мои торговые точки</Tab></div></div><main className="p-5">{tab === "profile" ? <div className="grid max-w-4xl gap-4 md:grid-cols-2"><section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><h1 className="font-bold">Мой профиль</h1><button onClick={() => setEdit(true)} className="rounded border p-2 text-[#15503A]"><Pencil className="h-4 w-4" /></button></div><div className="mt-6 flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-slate-200"><UserRound className="h-9 w-9 text-white" /></div><div><p className="font-semibold">{user.name || "Без имени"}</p><p className="text-sm text-slate-500">{user.role === "CASHIER" ? "Кассир" : user.role === "MANAGER" ? "Менеджер" : "Администратор"}</p></div></div><dl className="mt-7 space-y-4 text-sm"><div><dt className="text-slate-500">Имя</dt><dd className="mt-1 font-medium">{user.name || "—"}</dd></div><div><dt className="text-slate-500">Почта</dt><dd className="mt-1 font-medium">{user.email}</dd></div></dl><button onClick={() => setPassword(true)} className="mt-7 flex items-center gap-2 rounded bg-[#2abd62] px-4 py-2 text-sm font-bold text-white"><KeyRound className="h-4 w-4" />Сменить пароль</button></section><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="font-bold">Информация</h2><dl className="mt-6 grid gap-4 text-sm"><div><dt className="text-slate-500">Роль</dt><dd className="mt-1">{user.role === "CASHIER" ? "Кассир" : user.role}</dd></div><div><dt className="text-slate-500">Доступные магазины</dt><dd className="mt-1">{stores.length}</dd></div><div><dt className="text-slate-500">Вход в кассу</dt><dd className="mt-1"><a className="font-semibold text-[#15503A] underline" href="/kasa-giris">Открыть кассу</a></dd></div></dl></section></div> : <StoreList stores={stores} />}</main><EditProfileForm open={edit} onOpenChange={setEdit} user={user} /><ChangePasswordForm open={password} onOpenChange={setPassword} /></div>;
}
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`border-b-2 px-4 py-3 text-sm font-medium ${active ? "border-[#2abd62] text-[#15503A]" : "border-transparent text-slate-500"}`}>{children}</button>; }
function StoreList({ stores }: { stores: Store[] }) { return <div className="grid max-w-4xl gap-4 md:grid-cols-[260px_1fr]"><section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Торговые точки</h2><div className="mt-4 space-y-1">{stores.map((store) => <div key={store.id} className="rounded px-3 py-2 text-sm font-medium text-[#15503A]">{store.name}</div>)}{stores.length === 0 && <p className="text-sm text-slate-500">Магазины не назначены</p>}</div></section><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="font-bold">Где я работаю</h2>{stores.length ? <div className="mt-5 space-y-5">{stores.map((store) => <article key={store.id}><div className="flex items-center gap-2 font-semibold"><Building2 className="h-4 w-4 text-[#2abd62]" />{store.name}</div><dl className="mt-3 grid gap-2 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Статус</dt><dd className="text-[#168548]">Активный</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Адрес</dt><dd className="text-right">{store.address || "Не указан"}</dd></div></dl></article>)}</div> : <p className="mt-5 text-sm text-slate-500">Обратитесь к администратору, чтобы он назначил торговую точку.</p>}</section></div>; }
